version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000" # Map Django port to host port 8000
    volumes:
      - ./:/app # Mount your Django project directory
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    command: sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14.0-alpine # Postgres database

  frontend:
    build: ./react
    ports:
      - "3000:3000" # Map React port to host port 3000
    volumes:
      - ./students-fe:/app/frontend/ # Mount your React project directory
    depends_on:
      - django # React depends on Django service being up
    tty: true
    command: sh -c "yarn --cwd /app/frontend start"

volumes:
  postgres_data: # Optional persistent storage for database
